(function (root) {
  'use strict';
  const C = typeof module !== 'undefined' ? require('./chorus-state.js') : root.AfterimageChorus;
  const scene = (id, speaker, title, paragraphs) => ({ id: 'chorus.' + id, speaker, title, paragraphs });
  function record(s) { return [s.mode ? 'ROUTE / ' + C.modes[s.mode].title + '. ' + C.modes[s.mode].detail : 'ROUTE / Not connected.', 'GARDEN / ' + (s.incoming.open === 'evening' ? s.cycle === 1 ? 'Daylight and evenings, with Courier 024’s dusk check.' : s.evening === 'continue' ? 'Daylight and evenings. Courier 025 explicitly renewed the dusk check.' : 'Daylight continues. Evenings pause unless the new courier accepts the check with the retained sequence.' : 'Daylight hours. No evening duty assigned.'), 'TRANSIT / ' + (s.incoming.incoming.siltReturned ? 'Silt crossed back with the drawing.' : 'Silt remains on the far platform. A written copy of the drawing can travel without its author.')]; }
  const api = {
    record,
    arrival: s => scene('arrival', 'CHORUS / A PLACE TO DISAGREE', 'Three replies are waiting.', ['Counter has held one maintenance window open. Residents need their lamps, maintenance needs the carrier isolated, and dispatch needs to know when a route is safe to use.', 'The board can join their replies in three different ways. Choose a route, request a pause, read the acknowledgements, then open the inspection line.', ...record(s)]),
    counter: s => scene('counter', 'COUNTER', s.cycle === 1 ? '“A queue is a way of not losing someone.”' : s.kept.includes('counter') ? '“You remember why I wanted the desk.”' : '“Then I should explain the desk again.”', [s.cycle === 1 ? '“If we all ask maintenance separately, someone will mistake the third request for a different fault. I put them together. That helps.” Counter squares three slips of paper, then deliberately leaves the corners uneven.' : s.kept.includes('counter') ? 'You remember Counter putting three requests together so no one would repair the same fault three times.' : 'Counter tells Courier 025 why the requests were gathered. A new explanation does not become a remembered conversation.', '“My intake also refused a drawing. It had no fault code. I called that unusable. Silt called it a warning.”', '“Whichever route you choose, give the drawing somewhere to be read.”']),
    receiver: s => scene('receiver', 'UNADDRESSED RECEIVER', s.cycle === 1 ? 'The designation field is blank.' : s.kept.includes('address') ? 'You remember this voice.' : 'Courier 025 has no memory of this voice.', s.cycle === 1 ? [s.incoming.seatEcho ? 'The receiver pauses for as long as you paused beside the empty seat.' : 'There is a pause where the courier designation would normally be read.', '“I am not addressing designation 024. I mean whoever keeps choosing which of us remembers.”', 'Counter is still sorting slips at the next desk. The voice is in this receiver alone.', '“You do not have to explain what you are. Leave a little room in the next answer.”'] : [s.kept.includes('address') ? 'The courier recognizes the blank designation and the request for room.' : 'The courier reads a blank designation. The earlier address remains an experience you encountered; it has not returned to this instance.', s.reply === 'listen' ? 'The written response is: “I will listen before deciding what to keep.”' : s.reply === 'space' ? 'The written response is: “I will leave this answer open.”' : 'The response field will accept a promise to listen, or space left open. Neither restores a released memory.']),
    ack: (s, group) => {
      const lines = { residents: 'Residents: the garden lamps may pause for this inspection window. Daylight access remains. This is permission for one operation, not permanent closure.', maintenance: 'Maintenance: the carrier is isolated. The inspection line can open after all three acknowledgements. No cause has yet been established.', dispatch: 'Dispatch: deliveries are held at the marked stops for this window. Do not mark an unvisited platform empty.' };
      return scene('ack-' + group, 'COORDINATION / ACKNOWLEDGEMENT', group === 'combined' ? 'Counter’s combined envelope.' : group[0].toUpperCase() + group.slice(1) + ' reply.', group === 'combined' ? [lines.residents, lines.maintenance, lines.dispatch, 'The desk has combined the acknowledgements. Silt’s rejected warning still needs its own place in the evidence report.'] : [lines[group]]);
    },
    handoff: s => scene('handoff', 'COURIER HANDOFF', 'The report can travel without its author.', ['The inspection line is open. The report records an inhabited garden, a filtered warning, and a cause that is not established.', 'Choose two of the four experiences. The route, original evidence, and signed acknowledgements remain outside those slots.', s.incoming.open === 'evening' ? 'Courier 024’s dusk duty ends at this handoff. Evening use pauses unless Courier 025 retains the sequence and explicitly accepts the check.' : 'The garden stays on daylight hours; no evening duty is inherited.']),
    receipt: s => scene('receipt', 'CHORUS / HANDOFF COMPLETE', 'Agreement with room in it.', [...record(s), 'REPORT / Inhabited garden. Warning filtered out. Cause of carrier loss not established.', s.reply === 'listen' ? 'RESPONSE / A promise to listen before choosing.' : 'RESPONSE / Room left for an answer.', 'Release will ask which part of this work should continue.'])
  };
  root.AfterimageChorusStory = api; if (typeof module !== 'undefined') module.exports = api;
})(typeof globalThis !== 'undefined' ? globalThis : this);
