(function () {
  'use strict';
  const $ = id => document.getElementById(id), M = window.Afterimage3DState, Story = window.Afterimage3DChapters;
  const names = {prologue:'Prologue',transit:'Transit',garden:'Garden',chorus:'Chorus',release:'Release'};
  const pages = {prologue:'index-3d.html',transit:'transit-3d.html',garden:'garden-3d.html',chorus:'chorus-3d.html',release:'release-3d.html'};
  const entry = document.body.dataset.chapter || 'prologue', reduced = matchMedia('(prefers-reduced-motion: reduce)').matches;
  let s, saved = null, storedRaw = null, active = false, panelOpen = false, engine, focus = null, currentObject = null, escapeAction = null, focusReturn = null, tracked = null, toastTimer, audio = null, ambient = null, soundOn = false, soundBusy = false, soundWanted = false, melodyNodes = [], storageOK = true;
  function valid(value) { const result = M.validate(value); if (!result) throw new Error('This is not a valid 3D campaign save.'); return result; }
  function toast(message) { $('toast').textContent = message; $('toast').hidden = false; clearTimeout(toastTimer); toastTimer = setTimeout(() => { $('toast').hidden = true; }, 4500); }
  function fatal(message) { $('fatal').replaceChildren(); const p = document.createElement('p'); p.textContent = message; const a = document.createElement('a'); a.href = 'index.html'; a.textContent = 'Play the original edition'; $('fatal').append(p,a); $('fatal').hidden = false; }
  if (!M || !Story || !window.Afterimage3DWorld) { fatal('The 3D files could not load. Refresh the page, or open this edition through the local game server.'); return; }
  try { storedRaw = localStorage.getItem(M.key); if (storedRaw) saved = valid(JSON.parse(storedRaw)); } catch (error) { storageOK = error.name !== 'SecurityError'; $('save-warning').textContent = storageOK ? 'Your 3D save could not be read. It has not been replaced. Import a backup or choose a new beginning.' : 'Browser saving is unavailable. Export your progress from the menu before closing.'; $('save-warning').hidden = false; }
  s = saved?.chapter === entry ? valid(saved) : entry === 'prologue' ? M.fresh() : M.preview(entry);
  function save() { if (!active) return; try { localStorage.setItem(M.key, JSON.stringify(s)); saved = structuredClone(s); storedRaw = JSON.stringify(s); } catch (_) { if (storageOK) toast('Saving is unavailable. Export the 3D campaign from the menu.'); storageOK = false; } }
  function position() { if (engine) s.position = engine.getPosition(); }
  function updateFocus(object) { focus = object; const enabled = active && !panelOpen && Boolean(object); $('interact').hidden = !enabled; $('focus-label').textContent = object?.label || 'Interact'; $('touch-interact').disabled = !enabled; $('touch-interact').textContent = object?.label || 'Interact'; $('crosshair').classList.toggle('active', enabled); }
  try { engine = window.Afterimage3DWorld.create($('world'), { reducedMotion:reduced, onFocus:updateFocus, onInteract:id => { if (active && !panelOpen) encounter(id); }, onMove:p => { if (active) { s.position = {...p}; save(); } }, onError:fatal }); engine.load(Story.world(s), s.position); engine.pause(true); } catch (error) { fatal('This device could not start the 3D view. ' + error.message); return; }
  function hud() {
    const task = M.objective(s); $('chapter-label').textContent = names[s.chapter] + ' / ' + (s.phase === 'return' ? 'AFTER THE RESET' : s.phase === 'finished' ? 'OUTCOME RECORDED' : 'YOUR ASSIGNMENT'); $('order').textContent = task.order || names[s.chapter]; $('step').textContent = task.step || ''; $('tension').textContent = task.tension || ''; $('tension').hidden = !task.tension;
    $('progress').replaceChildren(); const total = Math.min(12,Math.max(0,Number(task.total)||0)), completed = Math.max(0,Number(task.completed)||0); for(let i=0;i<total;i++){const mark=document.createElement('i');if(i<completed)mark.className='done';$('progress').append(mark);}
    const held = s.phase === 'work' ? s.acquired : s.kept, lost=s.phase==='work'?[]:s.acquired.filter(id=>!s.kept.includes(id)); $('memory-caption').textContent = s.phase === 'work' ? held.length + ' memories found / 2 can continue' : '2 retained / '+lost.length+' released'; $('memory-list').textContent = held.map(id => M.memories[id]?.title || id).join(' · ') || 'No memories found yet';$('memory-list').title=lost.length?'Released: '+lost.map(id=>M.memories[id].title).join(', '):'';
  }
  function refreshWorld(useStatePosition = false) { const p = useStatePosition ? s.position : engine.getPosition(); engine.load(Story.world(s),p); s.position = engine.getPosition(); hud(); updateTracking(); }
  function closePanel() { panelOpen=false; $('panel').hidden=true; $('panel').classList.remove('menu'); document.body.classList.remove('reading'); $('hud').inert=false; $('cover').inert=false; escapeAction=null; if(active)engine.pause(false); if(active)$('world').focus();else if(focusReturn?.isConnected)focusReturn.focus(); focusReturn=null; updateFocus(focus); }
  function show(scene, choices, options={}) {
    if(!panelOpen)focusReturn=document.activeElement; panelOpen=true; engine.pause(true); updateFocus(null); document.body.classList.add('reading'); $('hud').inert=true; $('cover').inert=true; $('panel').hidden=false; $('panel').classList.toggle('menu',Boolean(options.menu)); $('panel').dataset.scene=scene.id||'';
    $('speaker').textContent=scene.speaker||names[s.chapter]; $('dialog-title').textContent=scene.title||''; $('lines').replaceChildren(); for(const line of scene.lines||scene.paragraphs||[]){const p=document.createElement('p');p.textContent=line.startsWith('[')?line.slice(1,-1):line;if(line.startsWith('['))p.className='note';$('lines').append(p);}
    $('puzzle').replaceChildren();$('puzzle').hidden=true; $('choices').replaceChildren(); $('choices').classList.toggle('compact',Boolean(options.compact)); for(const choice of choices||[]){const button=document.createElement('button');button.textContent=choice.label;button.disabled=Boolean(choice.disabled);if(choice.primary)button.classList.add('primary');if(choice.danger)button.classList.add('danger');if(choice.selected!==undefined)button.setAttribute('aria-pressed',String(choice.selected));if(choice.detail){const d=document.createElement('small');d.textContent=choice.detail;button.append(d);}button.addEventListener('click',()=>{try{choice.run?choice.run():execute(choice);}catch(e){toast(e.message);}});$('choices').append(button);}
    escapeAction=options.escape||closePanel; document.querySelector('.dialog').scrollTop=0; $('choices').querySelector('button:not(:disabled)')?.focus();
  }
  const leave=(label='Step away')=>({label,run:closePanel});
  function encounter(id, feedback=[]) { currentObject=id; const scene=Story.encounter(s,id); if(!scene)return toast('Nothing to use here yet.');const choices=[...(scene.choices||[])];if(!choices.some(c=>c.action==='$close'))choices.push(leave(scene.kind==='ending'?'Keep exploring':'Step away'));show({...scene,lines:[...(scene.lines||[]),...feedback]},choices);if(scene.puzzle)renderPuzzle(scene.puzzle,id); }
  function renderPuzzle(puzzle,id) {
    const key = puzzle.id || puzzle, config = M.puzzles?.[key] || {}, bits = s.flags[key+'Circuit'] || 0; $('puzzle').hidden=false; const clue=document.createElement('p');clue.className='puzzle-clue';const target=Number.isInteger(config.target)?config.target:5;const labels=config.labels||['Left','Middle','Right'];clue.textContent=puzzle.hint||config.hint||('The plate shows: '+labels.map((label,i)=>label+' '+((target>>i)&1?'on':'off')).join(', ')+'.');$('puzzle').append(clue);
    const row=document.createElement('div');row.className='switches';row.setAttribute('role','group');row.setAttribute('aria-label','Repair switches');for(let i=0;i<3;i++){const button=document.createElement('button');button.setAttribute('aria-pressed',String(Boolean(bits&(1<<i))));button.textContent=labels[i]||'Switch '+(i+1);const value=document.createElement('span');value.textContent=bits&(1<<i)?'●':'○';button.append(value);const status=document.createElement('small');status.textContent=bits&(1<<i)?'ON':'OFF';button.append(status);button.addEventListener('click',()=>{try{s=M.act(s,'turn',{id:key,index:i});save();refreshWorld();encounter(id);$('puzzle').querySelectorAll('.switches button')[i]?.focus();}catch(e){toast(e.message);}});row.append(button);} $('puzzle').append(row);
    const status=document.createElement('p');status.className='circuit-status';status.setAttribute('role','status');status.textContent=bits===target?'The controls match. Confirm the repair below.':'Match the controls to the plate, then confirm the repair.';$('puzzle').append(status);const help=document.createElement('button');help.textContent='Set the controls for me';help.addEventListener('click',()=>{try{for(let i=0;i<3;i++)if(Boolean(s.flags[key+'Circuit']&(1<<i))!==Boolean(target&(1<<i)))s=M.act(s,'turn',{id:key,index:i});save();refreshWorld();encounter(id);}catch(e){toast(e.message);}});$('puzzle').append(help);
  }
  function execute(choice, confirmed=false) {
    if(choice.confirm&&!confirmed){const c=choice.confirm;show({id:'review-'+choice.action,speaker:'REVIEW YOUR DECISION',title:c.title||'Confirm this choice?',lines:c.lines||[]},[{label:c.label||'Confirm this choice',primary:true,danger:choice.danger,run:()=>execute(choice,true)},{label:'Reconsider',run:()=>encounter(currentObject)}],{menu:true,escape:()=>encounter(currentObject)});return;}
    switch(choice.action){case '$close':return closePanel();case '$listen':return listenAgain();case '$scene':{const destination=Story.world(s).objects.find(o=>o.id===choice.value);if(destination&&Math.hypot(destination.x-engine.getPosition().x,destination.z-engine.getPosition().z)>2.6){tracked=destination.id;closePanel();updateTracking();toast('Walk to '+destination.label+'.');return;}return encounter(choice.value);}case '$journal':return journal();case '$reset':return chooseMemories();case '$advance':return advance();case '$ending':return ending();case '$sit':{try{if(choice.stateAction){s=M.act(s,choice.stateAction,choice.stateValue);save();refreshWorld();}const seat=choice.value||Story.world(s).objects.find(o=>o.kind==='bench');closePanel();if(seat){engine.sit({...seat,yaw:seat.yaw??s.position.yaw,pitch:seat.pitch??0});$('stand').hidden=false;toast('You can stay for a while. Move or choose Stand up when ready.');}return;}catch(e){return toast(e.message);}}default:if(!choice.action)return;
    }
    try{position();const phase=s.phase,acquired=s.acquired.slice();s=M.act(s,choice.action,choice.value);save();refreshWorld(phase!==s.phase);if(s.phase==='finished')return ending();if(choice.close){closePanel();return;}const feedback=s.acquired.filter(id=>!acquired.includes(id)).map(id=>'[Memory found: '+M.memories[id].title+'. '+M.memories[id].description+']');encounter(choice.next||currentObject,feedback.filter(line=>!(Story.encounter(s,choice.next||currentObject)?.lines||[]).some(existing=>existing.startsWith('[Memory found:'))));if(s.chapter==='prologue'&&choice.action==='receiver'){if(soundOn)playNotes();else toast('The song is recorded. Turn sound on in this panel to hear its four notes.');}}catch(error){toast(error.message);}
  }
  function chooseMemories(selected=[]) { if(!M.canReset(s))return toast(M.objective(s).step);const candidates=[...s.acquired];show({id:'choose-memories',speaker:'TWO MEMORIES CONTINUE',title:'What will you carry?',lines:['Keep two memories. You will lose the others. Objects, repairs, and other people keep their own history.']},[...candidates.map(id=>({label:M.memories[id]?.title||id,detail:M.memories[id]?.description||'',selected:selected.includes(id),run:()=>chooseMemories(selected.includes(id)?selected.filter(k=>k!==id):selected.length<2?[...selected,id]:[selected[1],id])})),{label:'Review what you will lose',primary:true,disabled:selected.length!==2,run:()=>reviewReset(selected)},leave('Not yet')],{menu:true}); }
  function reviewReset(pair) { const lost=s.acquired.filter(id=>!pair.includes(id));show({id:'confirm-reset',speaker:'CONFIRM THE RESET',title:'These memories will not continue.',lines:lost.map(id=>(M.memories[id]?.title||id)+': '+(M.memories[id]?.loss||'You will no longer remember this experience.')).concat('Your next instance keeps only the two memories you selected.')},[{label:'Keep these two and reset',primary:true,run:()=>{try{const next=M.reset(s,pair);closePanel();engine.pause(true);$('fade').classList.add('on');setTimeout(()=>{s=next;tracked=null;$('stand').hidden=true;refreshWorld(true);save();$('fade').classList.remove('on');engine.pause(false);toast('A new instance. Look at what stayed.');},reduced?0:260);}catch(e){toast(e.message);}}},{label:'Reconsider',run:()=>chooseMemories(pair)}],{menu:true,escape:()=>chooseMemories(pair)}); }
  function ending() { const record=s.history[s.history.length-1],report=Story.outcome(s,record),final=s.chapter==='release';show({id:'chapter-outcome',speaker:names[s.chapter].toUpperCase()+' / OUTCOME',title:report.title,lines:report.lines},[...(!final?[{label:'Continue to '+names[M.chapters[M.chapters.indexOf(s.chapter)+1]],primary:true,run:advance}]:[]),leave(final?'Stay in this place':'Look around before leaving'),{label:'Export the 3D campaign',run:exportSave}],{menu:true}); }
  function advance() { try{s=M.advance(s);save();location.href=pages[s.chapter];}catch(e){toast(e.message);} }
  function memoryNotes(){const held=s.phase==='work'?s.acquired:s.kept, lost=s.phase==='work'?[]:s.acquired.filter(id=>!s.kept.includes(id));return [...held.map(id=>(s.phase==='work'?'Memory found: ':'Retained: ')+M.memories[id].title+'. '+M.memories[id].description),...lost.map(id=>'Released: '+M.memories[id].title+'. '+M.memories[id].loss)];}
  function journal() { const task=M.objective(s),destinations=Story.journal(s);show({id:'field-journal',speaker:'FIELD JOURNAL / '+names[s.chapter].toUpperCase(),title:task.order,lines:[task.step,...(task.tension?[task.tension]:[]),...memoryNotes()]},[...destinations.map(d=>({label:'Track '+d.label,detail:d.detail||'',run:()=>{tracked=d.id;closePanel();updateTracking();}})),{label:'Read the campaign record',run:record},leave('Close the journal')],{menu:true}); }
  function record() { show({id:'campaign-record',speaker:'WHAT CARRIES FORWARD',title:'The record is still here.',lines:s.history.length?s.history.flatMap(r=>{const report=Story.outcome(s,r);return [names[r.chapter]+' / '+report.title,...report.lines];}):['No chapter has ended yet.']},[{label:'Back to journal',run:journal},leave()],{menu:true}); }
  function updateTracking() { if(!tracked||!active){$('tracked').hidden=true;return;}const obj=Story.world(s).objects.find(o=>o.id===tracked);if(!obj){tracked=null;$('tracked').hidden=true;return;}const p=engine.getPosition(),dx=obj.x-p.x,dz=obj.z-p.z;let angle=Math.atan2(dx,-dz)-p.yaw;angle=Math.atan2(Math.sin(angle),Math.cos(angle));const arrow=Math.abs(angle)<.25?'↑':Math.abs(angle)>2.6?'↶':angle>0?'→':'←';$('tracked').textContent=arrow+' '+obj.label+' · '+Math.hypot(dx,dz).toFixed(1)+' m';$('tracked').hidden=false; }
  setInterval(()=>{if(active&&!panelOpen)updateTracking();},300);
  function exportSave() { position();const data=active?s:saved||s;const blob=new Blob([JSON.stringify(data,null,2)],{type:'application/json'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download='afterimage-'+data.chapter+'-3d.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000); }
  function menu() { show({id:'menu',speaker:'AFTERIMAGE / FIRST PERSON',title:'Take the time you need.',lines:['WASD moves. Click or drag the scene to look. Arrow keys also work. Page Up / Down tilts the view; Home levels it. E interacts; J opens the journal.','Your assignment stays at the top left. Track a destination in the journal if you need help finding it.','This edition uses its own campaign save.']},[leave(active?'Return to the world':'Return to title'),...(active?[{label:'Field journal',run:journal},{label:'Review the chapter outcome',disabled:s.phase!=='finished',run:ending}]:[]),{label:'Export the 3D campaign',disabled:!active&&!saved,run:exportSave},{label:'Import a 3D campaign',run:()=>$('import-file').click()},{label:'Choose a chapter preview',run:previews},{label:'Start a new prologue',run:()=>confirmStart('prologue')}],{menu:true}); }
  function previews() { show({id:'chapter-previews',speaker:'FIRST-PERSON EDITION',title:'Choose a place to begin.',lines:['A chapter preview supplies a sample history for earlier chapters. Start at the prologue to make every choice yourself.']},M.chapters.map(chapter=>({label:chapter==='prologue'?'Start at the prologue':'Preview: '+names[chapter],run:()=>confirmStart(chapter)})).concat(leave('Cancel')),{menu:true}); }
  function confirmStart(chapter) { const candidate=chapter==='prologue'?M.fresh():M.preview(chapter);show({id:'confirm-start',speaker:'BEGIN A 3D CAMPAIGN',title:chapter==='prologue'?'Enter Archive 07?':'Preview '+names[chapter]+'?',lines:[...(active||storedRaw?['This replaces your current 3D campaign. Export it first if you want to keep it.']:[]),chapter==='prologue'?'You will begin at the first assignment.':'This preview uses a sample outcome from each earlier chapter.','The original edition has a separate save.']},[{label:'Begin '+names[chapter],primary:true,run:()=>{s=candidate;active=true;save();if(chapter!==entry){location.href=pages[chapter];return;}closePanel();begin(true);}},leave('Cancel')],{menu:true}); }
  function begin(intro=false) { active=true;if(soundWanted&&!soundOn)setSound(true,false);$('cover').hidden=true;$('hud').hidden=false;document.body.classList.add('playing');refreshWorld(true);engine.pause(false);save();$('world').focus();if(s.phase==='finished')ending();else if(intro){const task=M.objective(s);show({id:'arrival',speaker:'ASSIGNMENT / '+names[s.chapter].toUpperCase(),title:task.order,lines:[task.step,'Look around. Read the notices and speak with the people here before deciding how to finish.']},[leave('Begin the assignment')]);} }
  $('start').textContent=saved?'Continue '+names[saved.chapter]:entry==='prologue'?'Enter Archive 07':'Start '+names[entry]+' preview';$('cover-chapter').textContent=names[entry];
  $('start').addEventListener('click',()=>{if(saved){if(saved.chapter!==entry){location.href=pages[saved.chapter];return;}s=valid(saved);begin(false);}else confirmStart(entry);});$('previews').addEventListener('click',previews);$('menu-button').addEventListener('click',menu);$('journal').addEventListener('click',journal);$('interact').addEventListener('click',()=>engine.interact());$('touch-interact').addEventListener('click',()=>engine.interact());$('stand').addEventListener('click',()=>{engine.sit(null);$('stand').hidden=true;});
  $('import-file').addEventListener('change',async event=>{const file=event.target.files[0];event.target.value='';if(!file)return;try{if(file.size>1500000)throw new Error('This file is too large for a campaign save.');const candidate=valid(JSON.parse(await file.text()));show({id:'confirm-import',speaker:'IMPORT 3D CAMPAIGN',title:'Continue this campaign?',lines:[names[candidate.chapter]+' / '+candidate.phase,'This replaces your current 3D campaign. The original edition stays separate.']},[{label:'Import and continue',primary:true,run:()=>{s=candidate;active=true;save();if(s.chapter!==entry){location.href=pages[s.chapter];return;}closePanel();begin(false);}},leave('Cancel')],{menu:true});}catch(e){show({id:'invalid-import',speaker:'IMPORT FAILED',title:'The file could not be used.',lines:[e.message,'Your saved progress has not changed.']},[leave('Return')],{menu:true});}});
  document.addEventListener('keydown',event=>{if(panelOpen){if(event.key==='Escape'){event.preventDefault();escapeAction?.();}else if(event.key==='Tab'){const buttons=[...$('panel').querySelectorAll('button:not(:disabled)')];if(!buttons.length)return;const first=buttons[0],last=buttons[buttons.length-1];if(event.shiftKey&&document.activeElement===first){event.preventDefault();last.focus();}else if(!event.shiftKey&&document.activeElement===last){event.preventDefault();first.focus();}}return;}if(!active)return;if(event.key.toLowerCase()==='j'){event.preventDefault();journal();}else if(event.key==='Escape'&&!document.pointerLockElement){event.preventDefault();menu();}if(['w','a','s','d','ArrowUp','ArrowDown'].includes(event.key))$('stand').hidden=true;});
  const moves=new Map();function touchMove(){let forward=0,strafe=0;for(const value of moves.values()){if(value==='forward')forward++;if(value==='back')forward--;if(value==='right')strafe++;if(value==='left')strafe--;}engine.setMove(forward,strafe);if(forward||strafe)$('stand').hidden=true;}
  for(const button of $('move-pad').querySelectorAll('button')){button.addEventListener('pointerdown',event=>{event.preventDefault();button.setPointerCapture(event.pointerId);moves.set(event.pointerId,button.dataset.move);touchMove();});for(const eventName of ['pointerup','pointercancel','lostpointercapture'])button.addEventListener(eventName,event=>{moves.delete(event.pointerId);touchMove();});}
  let lookPointer=null;$('look-pad').addEventListener('pointerdown',e=>{e.preventDefault();$('look-pad').setPointerCapture(e.pointerId);lookPointer={id:e.pointerId,x:e.clientX,y:e.clientY};});$('look-pad').addEventListener('pointermove',e=>{if(!lookPointer||lookPointer.id!==e.pointerId)return;engine.look(e.clientX-lookPointer.x,e.clientY-lookPointer.y);lookPointer={id:e.pointerId,x:e.clientX,y:e.clientY};});for(const eventName of ['pointerup','pointercancel','lostpointercapture'])$('look-pad').addEventListener(eventName,()=>lookPointer=null);
  // Match the original prologue's four-note phrase; all sound remains opt-in.
  const soundKey='afterimage.sound.3d.v1';
  try{soundWanted=localStorage.getItem(soundKey)==='on';}catch(_){}
  const dialogSound=document.createElement('button');dialogSound.id='dialog-sound';dialogSound.className='dialog-sound';$('speaker').after(dialogSound);
  function soundButtons(){for(const button of [$('sound'),dialogSound]){button.textContent=soundOn?'Sound on':'Sound off';button.setAttribute('aria-pressed',String(soundOn));button.disabled=soundBusy;}}
  function stopNotes(){for(const node of melodyNodes){try{node.stop();}catch(_){}node.disconnect();}melodyNodes=[];}
  function playNotes(){
    if(!soundOn||!audio||audio.state!=='running')return;
    stopNotes();
    [329.63,293.66,220,246.94].forEach((hz,i)=>{const oscillator=audio.createOscillator(),gain=audio.createGain(),t=audio.currentTime+i*.47;
      oscillator.type='sine';oscillator.frequency.value=hz;gain.gain.setValueAtTime(0,t);gain.gain.linearRampToValueAtTime(.05,t+.025);gain.gain.exponentialRampToValueAtTime(.001,t+1.6);
      oscillator.connect(gain).connect(ambient);oscillator.start(t);oscillator.stop(t+1.7);melodyNodes.push(oscillator);oscillator.onended=()=>{oscillator.disconnect();gain.disconnect();melodyNodes=melodyNodes.filter(n=>n!==oscillator);};
    });
  }
  async function setSound(enabled=!soundOn,preview=true){
    if(soundBusy)return;soundBusy=true;soundButtons();
    try{
      if(enabled){
        if(!audio){const Audio=window.AudioContext||window.webkitAudioContext;if(!Audio)throw new Error('Audio is unavailable.');audio=new Audio();ambient=audio.createGain();ambient.gain.value=0;ambient.connect(audio.destination);
          (s.chapter==='prologue'?[110,164.81,220.3]:s.chapter==='transit'?[146.83,220,293.66]:[164.81,246.94,329.63]).forEach((hz,i)=>{const oscillator=audio.createOscillator(),gain=audio.createGain();oscillator.type='sine';oscillator.frequency.value=hz;gain.gain.value=s.chapter==='prologue'?.009/(i+1):s.chapter==='transit'?.007:.006;oscillator.connect(gain).connect(ambient);oscillator.start();});
        }
        await audio.resume();if(audio.state!=='running')throw new Error('Audio could not start.');ambient.gain.value=1;soundOn=true;
        if(preview&&s.chapter==='prologue'&&(s.phase==='work'||s.kept.includes('song')))playNotes();
      }else{soundOn=false;stopNotes();if(ambient)ambient.gain.value=0;if(audio)await audio.suspend();}
      soundWanted=enabled;try{localStorage.setItem(soundKey,enabled?'on':'off');}catch(_){}
    }catch(error){soundOn=false;soundWanted=false;if(ambient)ambient.gain.value=0;toast(error.message+' All clues remain available in text.');}
    finally{soundBusy=false;soundButtons();}
  }
  async function listenAgain(){if(soundOn){try{await audio.resume();playNotes();}catch(error){toast('Audio could not resume. Toggle sound to try again.');}}else await setSound(true);}
  $('sound').addEventListener('click',()=>setSound());dialogSound.addEventListener('click',()=>setSound());soundButtons();
  window.addEventListener('blur',()=>{moves.clear();touchMove();position();save();});document.addEventListener('visibilitychange',()=>{if(document.hidden){position();save();audio?.suspend();}else if(soundOn)audio?.resume().catch(()=>{});});window.addEventListener('pagehide',()=>{position();save();});hud();
})();
