(function (root) {
  'use strict';
  const R = typeof module !== 'undefined' ? require('./release-state.js') : root.AfterimageRelease;
  const GS = typeof module !== 'undefined' ? require('./garden-story.js') : root.AfterimageGardenStory;
  const CS = typeof module !== 'undefined' ? require('./chorus-story.js') : root.AfterimageChorusStory;
  const scene = (id, speaker, title, paragraphs) => ({ id: 'release.' + id, speaker, title, paragraphs });
  const garden = s => s.incoming.incoming;
  function record(s) { return [GS.archiveRecord(garden(s)), ...GS.transitRecord(garden(s)), ...CS.record(s.incoming)]; }
  function consequences(s, ending) {
    const g = garden(s), local = ending === 'remain';
    return [
      local ? 'SERVICE / The garden and public receiver stay linked through the agreed Chorus route. The unused long-distance dispatch branch closes.' : 'SERVICE / The shared carrier and public relay are retired. The repaired receiver remains physically here but carries no shared notices. Local resident spaces are explicit exceptions to closure.',
      'GARDEN / The shaded court and its public path stay open in daylight. The seat remains ' + GS.placeNames[g.place] + '.',
      local && s.incoming.evening === 'continue' ? 'EVENING / Courier 025’s explicitly renewed controller check supports evening use.' : 'EVENING / Lamps off. No evening use or dusk duty assigned.',
      local ? 'UPKEEP / Fern: morning shade check. Brim: morning receiver log. Counter: the offered route check. The courier keeps only an explicitly renewed dusk check.' : 'UPKEEP / Fern keeps the morning shade check. Brim’s shared-receiver log and the courier’s dusk check end with the retired service. Counter has no new maintenance job.',
      ending === 'witness' ? 'RECORD / A copy of the supported account leaves through the final outgoing window. Transmission does not establish receipt, carry residents, or promise rescue.' : 'RECORD / The supported report and original sources stay in the local record room.',
      g.incoming.siltReturned ? 'SILT / Already returned with the drawing. The drawing remains theirs; they have no assigned maintenance duty.' : 'SILT / Still on the far Transit platform with light and supplies. This plan does not create a crossing or claim that separation is solved.'
    ];
  }
  const api = {
    record, consequences, garden,
    arrival: s => scene('arrival', 'RELEASE / WHAT REMAINS UNFINISHED', 'The final order has a margin.', ['The shared carrier cannot keep every branch alive indefinitely. The order asks for a sustainable completion, and permits occupied local spaces to be named as exceptions.', 'Walk through the garden, archive record room, and service yard. Read what each plan would actually close before choosing.', 'There is no further memory reset. These two experiences are what Courier 025 carries into the decision.']),
    court: s => scene('court', 'FERN / THE GARDEN', '“The seat can stay.”', ['Fern tests the repaired shade, then puts the test card down. “That is the morning check. The next five minutes are mine.”', 'The seat remains ' + GS.placeNames[garden(s).place] + '.', s.kept.includes('fern') ? 'You remember the original invitation without a task.' : 'Fern offers Courier 025 a place to sit. This is an invitation in the present, whether or not the first one was retained.', 'Every proposed plan preserves the daylight garden. Evening lamps depend on a live local loop and the courier’s renewed check. The shared receiver falls silent if its carrier retires.']),
    archive: s => scene('archive', 'LOCAL RECORD ROOM', 'Read what actually remains.', ['INCOMING RECORD / These entries describe the completed earlier chapters. ' + (s.ending ? 'The settled service plan below governs current hours.' : 'The final service plan has not been chosen yet.'), ...record(s), ...(s.ending ? consequences(s, s.ending) : []), 'The Chorus evidence proves an inhabited garden and a warning excluded from the queue. It does not prove the cause of carrier loss.', 'Complete keeps this account here. Witness sends a copy beyond the network. Remain keeps it here beside a working local service. None of these choices reconstructs people or objects previously lost.']),
    yard: s => scene('yard', 'SERVICE YARD', 'Three things a hand can do.', ['The breaker retires the shared carrier. The outbox sends one final account before retirement. The local loop disconnects unused branches and keeps a smaller service running.', 'All three plans preserve occupied local spaces and the daylight garden. None reopens an unmade Transit crossing.', ...Object.values(R.endings).map(e => e.title + ': ' + e.detail)]),
    counter: s => scene('counter', 'COUNTER / AN OFFER', '“I can check the route.”', [s.kept.includes('counter') ? 'You remember why Counter wanted the shared queue. They still want to make missed requests visible.' : 'Counter explains the queue once more, without asking you to pretend you remember.', '“If you keep the local loop, I offer one route check each morning. I will keep the unformatted replies beside the numbered ones. I cannot take every unused branch.”', s.counterAgreement ? 'The offered morning route check is recorded for the Remain plan only.' : 'The offer needs to be recorded before a local loop can be committed. Other plans assign Counter no new job.']),
    question: s => scene('question', 'THE UNADDRESSED FIELD', 'Which part of this are you choosing to continue?', [s.kept.includes('address') ? 'The courier remembers the receiver that left its designation blank. The final form leaves the same space.' : 'The courier has read the plans. The question in the margin is addressed beyond the designation field.', 'You have seen the places each answer would leave. Choose a plan to review, then enact it at its marked control.', 'There is no answer that makes the earlier losses unhappen.']),
    coda: s => scene('coda', 'RELEASE / ' + s.ending.toUpperCase(), s.ending === 'complete' ? 'A finished report. An occupied margin.' : s.ending === 'witness' ? 'The account leaves. The people remain here.' : 'Tomorrow has names beside it.', [...consequences(s, s.ending), GS.archiveRecord(garden(s)), s.ending === 'remain' ? 'Counter folds the route check into the morning queue. Brim leaves room below the receiver log. Fern has already finished the shade check and is sitting down.' : 'Counter takes the retired queue off the desk. Brim closes the receiver log. Fern finishes the shade check and sits where the light is softer.', s.incoming.reply === 'listen' ? 'You left a promise to listen. The last scene gives you time to keep it.' : 'You left room for an answer. The seat does not fill that space for you.', '[End of this playable story. You can keep exploring the settled rooms or export the final record.]'])
  };
  root.AfterimageReleaseStory = api; if (typeof module !== 'undefined') module.exports = api;
})(typeof globalThis !== 'undefined' ? globalThis : this);
