const assert=require('node:assert/strict');
const path=require('node:path');
const {pathToFileURL}=require('node:url');
const {chromium}=require('@playwright/test');
const M=require('../state-3d.js');
const base=process.env.GAME_URL||pathToFileURL(path.resolve(__dirname,'../index-3d.html')).href;
let browser;const errors=[];
async function make(file='index-3d.html',seed=null){
 const context=await browser.newContext({viewport:{width:1280,height:800},reducedMotion:'reduce'});
 await context.addInitScript(()=>{
   window.audioAudit={contexts:[],notes:[],analyser:null};const Native=window.AudioContext;
   window.AudioContext=class extends Native{constructor(...args){super(...args);audioAudit.contexts.push(this);const analyser=this.createAnalyser();analyser.fftSize=2048;analyser.connect(this.destination);audioAudit.analyser=analyser;const create=this.createGain.bind(this);this.createGain=()=>{const gain=create(),connect=gain.connect.bind(gain);gain.connect=(target,...rest)=>connect(target===this.destination?analyser:target,...rest);return gain;};const osc=this.createOscillator.bind(this);this.createOscillator=()=>{const o=osc(),start=o.start.bind(o);o.start=t=>{audioAudit.notes.push(o.frequency.value);return start(t);};return o;};}};
   let world;Object.defineProperty(window,'Afterimage3DWorld',{configurable:true,get:()=>world,set:value=>{world=value;const create=value.create;value.create=(c,o)=>{window.openTestEncounter=o.onInteract;return create(c,o);};}});
 });
 const p=await context.newPage();p.on('pageerror',e=>errors.push(e.message));await p.goto(new URL(file,base).href);
 if(seed){await p.evaluate(([key,state])=>localStorage.setItem(key,JSON.stringify(state)),[M.key,seed]);await p.reload();}
 await p.locator('#start').click();
 if(file.endsWith('-3d.html')&&!seed){const chapter=file==='index-3d.html'?'Prologue':file[0].toUpperCase()+file.slice(1).split('-')[0];await p.getByRole('button',{name:'Begin '+chapter,exact:true}).click();await p.getByRole('button',{name:'Begin the assignment',exact:true}).click();}
 else if(file==='index.html'){const confirm=p.getByRole('button',{name:'Enter the room',exact:true});if(await confirm.isVisible())await confirm.click();}
 return p;
}
async function visit(p,id){if(await p.locator('#panel').isVisible())await p.keyboard.press('Escape');await p.evaluate(id=>openTestEncounter(id),id);}
async function saved(p){return p.evaluate(key=>JSON.parse(localStorage.getItem(key)),M.key);}
async function frequencies(p){return p.evaluate(()=>audioAudit.notes.slice());}
async function rms(p){return p.evaluate(()=>{const values=new Float32Array(audioAudit.analyser.fftSize);audioAudit.analyser.getFloatTimeDomainData(values);return Math.sqrt(values.reduce((s,v)=>s+v*v,0)/values.length);});}
(async()=>{
 browser=await chromium.launch({headless:true});
 const original=await make('index.html');await original.locator('#sound').click();const expected=(await frequencies(original)).slice(-4);assert.deepEqual(expected,[329.6300048828125,293.6600036621094,220,246.94000244140625]);await original.context().close();
 const p=await make();await visit(p,'service');await p.getByRole('button',{name:'Study the service route',exact:true}).click();assert.equal((await saved(p)).flags.service,true);assert.equal(await p.locator('#panel').isVisible(),false);assert.match(await p.locator('#toast').innerText(),/Memory found: The service route/);await visit(p,'service');assert.equal(await p.getByRole('button',{name:'Study the service route',exact:true}).count(),0);
 await visit(p,'moth');await p.getByRole('button',{name:'Introduce yourself',exact:true}).click();assert.equal((await saved(p)).flags.meet,true);assert.match(await p.locator('#dialog-title').innerText(),/remember you/);assert.match(await p.locator('#toast').innerText(),/Memory found: Moth’s name/);assert.doesNotMatch(await p.locator('#lines').innerText(),/Memory found|Retain it/);assert.equal(await p.getByRole('button',{name:'Introduce yourself',exact:true}).count(),0);
 await visit(p,'receiver');await p.getByRole('button',{name:'Listen to the whole tune',exact:true}).click();assert.match(await p.locator('#dialog-title').innerText(),/Four notes/);assert.equal((await saved(p)).flags.receiver,true);assert.deepEqual(await frequencies(p),[]);
 // Sound can be enabled without closing a dialogue; the actual graph has audible signal.
 await p.locator('#dialog-sound').click();assert.equal(await p.locator('#sound').getAttribute('aria-pressed'),'true');assert.deepEqual((await frequencies(p)).slice(-4),expected);await p.waitForTimeout(150);assert.ok(await rms(p)>.01,'melody must produce nonzero audible signal');
 const count=(await frequencies(p)).length;await p.getByRole('button',{name:'Listen again',exact:true}).click();assert.equal((await frequencies(p)).length,count+4);await p.locator('#dialog-sound').click();assert.equal(await p.evaluate(()=>audioAudit.contexts[0].state),'suspended');
 await p.locator('#dialog-sound').click();await p.reload();await p.locator('#start').click();await p.waitForFunction(()=>audioAudit.contexts[0]?.state==='running');assert.equal(await p.locator('#sound').getAttribute('aria-pressed'),'true');await visit(p,'service');assert.doesNotMatch(await p.locator('#lines').innerText(),/Memory found/);assert.equal(await p.getByRole('button',{name:'Study the service route',exact:true}).count(),0);
 await p.context().close();
 let state=M.fresh();for(const action of ['meet','flower','service','receiver'])state=M.act(state,action);state=M.reset(state,['name','route']);
 const lost=await make('index-3d.html',state);await visit(lost,'receiver');assert.match(await lost.locator('#dialog-title').innerText(),/Only static/);assert.equal(await lost.getByRole('button',{name:'Listen again',exact:true}).count(),0);await lost.locator('#dialog-sound').click();assert.equal((await frequencies(lost)).length,3,'lost melody must not be replayed');await lost.context().close();

 // Later chapters use their own ambient chord and never replay the Archive melody.
 for(const [chapter,notes] of [['transit',[146.83,220,293.66]],['garden',[164.81,246.94,329.63]],['chorus',[164.81,246.94,329.63]],['release',[164.81,246.94,329.63]]]){
   const page=await make(chapter+'-3d.html');await page.locator('#sound').click();assert.deepEqual((await frequencies(page)).map(n=>Math.round(n*100)/100),notes,chapter);await page.context().close();
 }
 const click=async(page,label)=>page.getByRole('button',{name:new RegExp('^'+label)}).click();
 const action=async(page,id,label)=>{await visit(page,id);await click(page,label);};
 const repaired=(state,id)=>{for(let i=0;i<3;i++)if(M.puzzles[id].target&(1<<i))state=M.act(state,'turn',{id,index:i});return M.act(state,id);};
 const prepareGarden=()=>{let s=M.preview('garden');for(const a of ['fern','morning','brim','seat'])s=M.act(s,a);s=repaired(s,'shade');s=repaired(s,'receiver');return M.act(s,'listen');};
 // Repaired relays must not be requested again by the service index after a real handoff.
 let archive=M.fresh();for(const a of ['meet','flower','service','receiver'])archive=M.act(archive,a);
 const preserved=await make('index-3d.html',repaired(repaired(archive,'relayA'),'relayB'));
 await action(preserved,'reset','Review the two-memory handoff');for(const id of ['name','song'])await click(preserved,M.memories[id].title);await click(preserved,'Review what you will lose');await click(preserved,'Keep these two and reset');await preserved.waitForFunction(key=>JSON.parse(localStorage.getItem(key)).phase==='return',M.key);
 await visit(preserved,'service');assert.match(await preserved.locator('#dialog-title').innerText(),/Both relays are repaired/);assert.doesNotMatch(await preserved.locator('#lines').innerText(),/Restore both|still needs|not yet secured/);assert.equal(await preserved.getByRole('button',{name:'Return to Moth',exact:true}).count(),1);
 for(const id of ['relayA','relayB']){assert.equal((await saved(preserved)).flags[id],true);await visit(preserved,id);assert.equal(await preserved.locator('.switches button').count(),0);assert.match(await preserved.locator('.circuit-status').innerText(),/Repair secured/);}
 await action(preserved,'moth','Answer Moth');await visit(preserved,'service');assert.equal(await preserved.getByRole('button',{name:'Review the closure control',exact:true}).count(),1);assert.doesNotMatch(await preserved.locator('#step').innerText(),/relay contacts/);await preserved.reload();await preserved.locator('#start').click();await visit(preserved,'service');assert.match(await preserved.locator('#dialog-title').innerText(),/Both relays are repaired/);await preserved.context().close();
 const repairedLater=await make('index-3d.html',M.act(M.reset(archive,['name','song']),'meet'));
 for(const id of ['relayA','relayB']){await action(repairedLater,id,'Set the controls for me');await click(repairedLater,'Secure the repair');await visit(repairedLater,'service');const text=await repairedLater.locator('#lines').innerText();assert.doesNotMatch(text,/Restore both/);if(id==='relayA'){assert.match(text,/West relay: repaired and secured/);assert.match(text,/Only the east relay/);}else{assert.match(await repairedLater.locator('#dialog-title').innerText(),/Both relays are repaired/);assert.equal(await repairedLater.getByRole('button',{name:'Review the closure control',exact:true}).count(),1);}}
 const fs=require('node:fs'),output=require('node:path').join(require('node:os').tmpdir(),'afterimage-verification');fs.mkdirSync(output,{recursive:true});await repairedLater.screenshot({path:require('node:path').join(output,'service-restored-3d.png')});await repairedLater.context().close();
 let quiet=M.reset(prepareGarden(),['fern','tuning']);const gardenQuiet=await make('garden-3d.html',quiet);await action(gardenQuiet,'receiver','Restore the quiet channel');assert.equal((await saved(gardenQuiet)).flags.quiet,true);assert.equal(await gardenQuiet.locator('#panel').getAttribute('data-scene'),'quiet-channel');assert.match(await gardenQuiet.locator('#lines').innerText(),/Silt answers/);await gardenQuiet.context().close();
 let proposal=M.reset(prepareGarden(),['sequence','fern']);const garden=await make('garden-3d.html',proposal);await action(garden,'certify','Set daylight opening hours');await click(garden,'Review evening opening');assert.equal((await saved(garden)).flags.evening,false);await click(garden,'Propose evening hours');assert.equal(M.gardenSchedule(await saved(garden)).evening,false);assert.match(await garden.locator('#lines').innerText(),/only a proposal/);await click(garden,'Accept my own dusk controller check');assert.equal((await saved(garden)).flags.duty,false);await click(garden,'Accept the dusk check');assert.equal(M.gardenSchedule(await saved(garden)).evening,true);await click(garden,'Inspect the court and public path');proposal=await saved(garden);await garden.context().close();
 let chorusSeed=M.advance(M.act(proposal,'finish','court'));const chorus=await make('chorus-3d.html',chorusSeed);await visit(chorus,'sources');assert.equal(await chorus.getByRole('button',{name:/^Record this evidence review/}).isDisabled(),true);const titles=require('../chapters-3d.js').sources.map(s=>s.title);for(const title of titles){await visit(chorus,'sources');await click(chorus,title);}await visit(chorus,'sources');await click(chorus,'Record this evidence review');assert.equal((await saved(chorus)).flags.evidence,true);await action(chorus,'route','Keep three local copies');await action(chorus,'residents','Record this approval');await visit(chorus,'route');assert.equal(await chorus.getByRole('button',{name:/^Keep three local copies/}).isDisabled(),true);await click(chorus,'Pass an ordered round');assert.equal((await saved(chorus)).flags.voices,1);await click(chorus,'Change to the ordered round');assert.equal((await saved(chorus)).flags.voices,0);chorusSeed=await saved(chorus);await chorus.context().close();
 for(const a of ['counter','receiver'])chorusSeed=M.act(chorusSeed,a);for(const i of [0,1,2])chorusSeed=M.act(chorusSeed,'voice',i);chorusSeed=M.reset(chorusSeed,['sequence','counter']);const returned=await make('chorus-3d.html',chorusSeed);await visit(returned,'counter');assert.match(await returned.locator('#lines').innerText(),/promise ended/);await click(returned,'Renew my dusk controller check');assert.equal(M.gardenSchedule(await saved(returned)).evening,false);await click(returned,'Renew my dusk check');assert.equal(M.gardenSchedule(await saved(returned)).evening,true);await action(returned,'receiver','Leave room for an answer');assert.equal((await saved(returned)).flags.addressReply,'space');await returned.keyboard.press('Escape');await returned.locator('#journal').click();assert.match(await returned.locator('#lines').innerText(),/Released:.*invitation/);assert.match(await returned.locator('#lines').innerText(),/Retained:/);assert.match(await returned.locator('#memory-caption').innerText(),/2 retained . 2 released/);await returned.context().close();
 let tuned=M.preview('chorus');for(const a of ['counter','receiver','evidence'])tuned=M.act(tuned,a);tuned=M.act(tuned,'mode','local');for(const i of [0,1,2])tuned=M.act(tuned,'voice',i);tuned=M.reset(tuned,['tuning','counter']);const privateReply=await make('chorus-3d.html',tuned);await action(privateReply,'counter','Hear Counter on the quiet channel');assert.match(await privateReply.locator('#lines').innerText(),/I kept the slip/);await privateReply.context().close();
 const release=await make('release-3d.html');for(const [id,label] of [['records','Record the archive and dispatch review'],['fern','Inspect the inhabited court'],['plan','Inspect the service yard and its controls']]){await action(release,id,label);assert.equal(await release.getByRole('button',{name:label,exact:true}).isVisible(),false);}await action(release,'witness','Enact witness');await click(release,'Enact the plan');await visit(release,'counter');assert.match(await release.locator('#lines').innerText(),/no new route job/);await visit(release,'fern');assert.match(await release.locator('#lines').innerText(),/no receipt has arrived/i);await visit(release,'receiver');assert.match(await release.locator('#lines').innerText(),/carrier has been retired/);await visit(release,'records');await release.locator('.scene-record summary').click();assert.match(await release.locator('#lines').innerText(),/Since those records arrived/);await visit(release,'seat');assert.equal(await release.locator('#panel').isVisible(),false);await click(release,'Stand up');assert.equal((await saved(release)).ending,'witness');await release.context().close();
 assert.deepEqual(errors,[]);console.log('Feedback/audio: original melody matched; real signal, mute, replay, preference restore, chapter ambience, visible choices, retained relay/service completion, Garden consent, Chorus evidence/replies/renewal, memory journal, and Release aftermath passed.');
})().catch(e=>{console.error(e);process.exitCode=1;}).finally(async()=>{await browser?.close();});
