const {test}=require('node:test'),assert=require('node:assert/strict');
const T=require('../transit-state.js'),G=require('../garden-state.js'),C=require('../chorus-state.js'),R=require('../release-state.js'),RS=require('../release-story.js');
const pairs=ids=>ids.flatMap((a,i)=>ids.slice(i+1).map(b=>[a,b]));
function prepare(s,mode='central'){for(const a of ['counter','hear'])C.act(s,a);C.act(s,'mode',mode);C.act(s,'align');C.act(s,'connect');C.act(s,'request');for(const g of mode==='central'?['combined']:C.groups)C.act(s,'ack',g);C.act(s,'operate');for(const id of Object.keys(C.evidence))C.act(s,'read',id);for(const [id,c] of Object.entries(C.claims))C.act(s,'claim',{id,answer:c.answer});return s;}
function finish(s){C.act(s,'counter');C.act(s,'review');C.act(s,'reply','listen');C.act(s,'evening',s.incoming.open==='daylight'?'none':s.kept.includes('sequence')?'continue':'pause');assert.equal(C.act(s,'release'),true);return s;}
function garden(origin,sort,tp,gp){let t=T.fresh(origin);for(const a of ['brim','silt','sequence','message'])T.act(t,a);T.act(t,'sort',sort);if(sort==='repairing'){T.act(t,'align');T.act(t,'secure');}t=T.reset(t,tp);T.act(t,'brim');T.act(t,'silt');if(tp.includes('sequence')){T.act(t,'bridge');T.act(t,'bring');}T.act(t,'deliver');let g=G.fresh(t);for(const a of ['fern','alignLight','latchShade','fernAgreement','alignReceiver','connect','listen','brimAgreement'])G.act(g,a);G.act(g,'place','gate');g=G.reset(g,gp);for(const a of ['fern','shade','receiver'])G.act(g,a);if(gp.includes('sequence'))G.act(g,'evening',true);G.act(g,'open',gp.includes('sequence')?'evening':'daylight');return g;}
test('8748 origin, document, retention, route and ending combinations preserve continuity',()=>{
 let n=0;for(const origin of T.origins)for(const sort of ['book','ledger','repairing'])for(const tp of pairs(Object.keys(T.memories)))for(const gp of pairs([...tp,'fern','tuning'])){
 const g=garden(origin,sort,tp,gp),original=JSON.stringify(g);
 for(const mode of Object.keys(C.modes)){const first=prepare(C.fresh(g),mode);assert.equal(C.ready(first),true);assert.deepEqual(C.validate(first),first);
 for(const cp of pairs(C.candidates(first))){const c=finish(C.reset(first,cp));assert.deepEqual(C.validate(c),c);assert.equal(c.evening,g.open==='daylight'?'none':cp.includes('sequence')?'continue':'pause');
 for(const ending of Object.keys(R.endings)){const r=R.fresh(c);assert.equal(R.act(r,'plan',ending),false);for(const room of R.rooms)R.act(r,'inspect',room);if(ending==='remain'){assert.equal(R.act(r,'plan',ending),false);R.act(r,'counterAgreement');}assert.equal(R.act(r,'plan',ending),true);assert.equal(r.ending,null);assert.equal(R.act(r,'enact',ending==='complete'?'outbox':'breaker'),false);assert.equal(R.act(r,'enact',R.endings[ending].object),true);R.act(r,'coda');assert.deepEqual(R.validate(JSON.parse(JSON.stringify(r))),r);assert.deepEqual(r.kept,cp);assert.equal(r.incoming.incoming.incoming.origin,origin);assert.equal(r.incoming.incoming.incoming.siltReturned,tp.includes('sequence'));assert.equal(R.act(r,'plan','complete'),false);assert.match(RS.coda(r).paragraphs.join(' '),/daylight/);n++;}
 }}assert.equal(JSON.stringify(g),original);
 }assert.equal(n,8748);
});
test('signal routes have one solution each; acknowledgement order and assistance are real',()=>{
 for(const mode of Object.keys(C.modes)){const s=C.preview('book');C.act(s,'mode',mode);let solutions=0;for(let a=0;a<3;a++)for(let b=0;b<3;b++)for(let c=0;c<3;c++){s.dials=[a,b,c];solutions+=Number(C.connected(s));}assert.equal(solutions,1);s.dials=[2,0,2];assert.equal(C.act(s,'operate'),false);C.act(s,'align');assert.equal(s.wired,false);assert.deepEqual(C.validate(s),s);C.act(s,'connect');assert.equal(C.act(s,'mode','local'),false);assert.equal(C.act(s,'dial',0),false);assert.equal(C.act(s,'ack','residents'),false);C.act(s,'request');if(mode==='round')assert.equal(C.act(s,'ack','dispatch'),false);if(mode==='central')assert.equal(C.act(s,'ack','residents'),false);for(const g of mode==='central'?['combined']:mode==='local'?['dispatch','residents','maintenance']:C.groups)assert.equal(C.act(s,'ack',g),true);assert.equal(s.operation,false);assert.equal(C.act(s,'operate'),true);}
});
test('claims require sources and unsupported certainty cannot cross a handoff',()=>{
 const s=C.preview('shelf');assert.equal(C.act(s,'claim',{id:'cause',answer:'proven'}),false);prepare(s);C.act(s,'claim',{id:'cause',answer:'proven'});assert.equal(C.ready(s),false);assert.throws(()=>C.reset(s,['counter','address']));assert.deepEqual(C.validate(s),s);C.act(s,'claim',{id:'cause',answer:'unknown'});assert.equal(C.ready(s),true);const c=C.reset(s,['counter','address']);assert.equal(c.acquired.includes('message'),false);assert.equal(C.act(c,'hear'),false);assert.equal(C.act(c,'claim',{id:'cause',answer:'proven'}),false);assert.deepEqual(c.report,s.report);
});
test('evening duties end at reset and need the procedure plus a fresh commitment',()=>{
 const first=prepare(C.preview('book'));for(const pair of [['sequence','address'],['counter','address']]){const s=C.reset(first,pair);assert.equal(s.evening,null);assert.equal(C.act(s,'release'),false);assert.equal(C.act(s,'evening','none'),false);assert.equal(C.act(s,'evening','continue'),pair.includes('sequence'));assert.equal(C.act(s,'evening','pause'),true);assert.equal(s.evening,'pause');C.act(s,'counter');C.act(s,'review');C.act(s,'reply','space');C.act(s,'release');const r=R.fresh(s);assert.match(RS.consequences(r,'remain').join(' '),/No evening use/);}
});
test('seat address is one-time, optional, and compatible with old Garden saves',()=>{
 const open=C.preview('book').incoming;const s=structuredClone(open);s.open=null;s.evening=false;s.courierDuty=false;s.reunion=false;assert.equal(s.kept.includes('fern'),false);assert.equal(G.act(s,'seatEcho'),true);const held=[...s.acquired];assert.equal(G.act(s,'seatEcho'),false);assert.deepEqual(s.acquired,held);G.act(s,'fern');assert.equal(G.validate(s).seatEcho,true);const old=structuredClone(open);delete old.seatEcho;assert.equal(G.validate(old).seatEcho,false);const afterFern=structuredClone(open);afterFern.open=null;assert.equal(G.act(afterFern,'seatEcho'),false);const kept=structuredClone(C.preview('ledger').incoming);kept.open=null;kept.reunion=false;assert.equal(G.act(kept,'seatEcho'),false);kept.seatEcho=true;assert.throws(()=>G.validate(kept));
});
test('malformed Chorus and Release saves cannot invent progress, memories, agreements or endings',()=>{
 const good=C.reset(prepare(C.preview('book')),['counter','address']);for(const edit of [s=>s.kind='wrong',s=>s.incoming.open=null,s=>s.mode=null,s=>s.dials=[0,0,0],s=>s.acks=[],s=>s.read=[],s=>s.report.cause='proven',s=>s.acquired.push('sequence'),s=>s.evening='continue',s=>s.evening='none',s=>s.released=true,s=>s.player.x=NaN,s=>s.reunion='yes']){const s=structuredClone(good);edit(s);const before=JSON.stringify(s);assert.throws(()=>C.validate(s));assert.equal(JSON.stringify(s),before);}
 const goodR=R.preview('book');for(const edit of [s=>s.incoming.released=false,s=>s.kept=['address','address'],s=>s.acquired=['counter','address'],s=>s.plan='remain',s=>s.ending='complete',s=>s.coda=true,s=>s.visited=['court','court'],s=>s.room='relay',s=>s.player.y=999]){const s=structuredClone(goodR);edit(s);assert.throws(()=>R.validate(s));}
});
test('all final plans can be reconsidered; no report or prior loss is silently rewritten',()=>{
 for(const id of ['book','ledger','shelf']){const r=R.preview(id),before=JSON.stringify(r.incoming);for(const room of R.rooms)R.act(r,'inspect',room);R.act(r,'counterAgreement');for(const ending of Object.keys(R.endings)){R.act(r,'plan',ending);assert.equal(r.ending,null);assert.deepEqual(R.validate(r),r);R.act(r,'cancel');assert.equal(r.plan,null);}assert.equal(JSON.stringify(r.incoming),before);const text=RS.consequences(r,'witness').join(' ');assert.match(text,/does not establish receipt/);assert.match(text,/No evening use/);if(id==='ledger')assert.match(RS.record(r).join(' '),/residents have not been restored/);}
});
