const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),os=require('node:os');
const {pathToFileURL}=require('node:url');const {chromium}=require(process.env.PLAYWRIGHT_MODULE||'@playwright/test');
const G=require('../garden-state.js'),T=require('../transit-state.js'),S=require('../state.js');
const base=process.env.GAME_URL||pathToFileURL(path.resolve(__dirname,'../index.html')).href,url=new URL('garden.html',base).href;
const output=path.join(os.tmpdir(),'afterimage-verification');fs.mkdirSync(output,{recursive:true});const errors=[];let browser,lastPage;
const button=(p,name)=>p.getByRole('button',{name,exact:true}),stored=p=>p.evaluate(k=>JSON.parse(localStorage.getItem(k)),G.key);
async function newPage(seed,viewport={width:1440,height:960}){const context=await browser.newContext({viewport,reducedMotion:'reduce',acceptDownloads:true});const p=await context.newPage();lastPage=p;p.on('pageerror',e=>errors.push(e.message));p.on('request',r=>{if(/^https?:/.test(r.url())&&!r.url().startsWith(new URL(url).origin))errors.push('External request: '+r.url());});await p.goto(url);if(seed){await p.evaluate(([k,s])=>localStorage.setItem(k,JSON.stringify(s)),[G.key,seed]);await p.reload();}return p;}
async function close(p){await p.keyboard.press('Escape');await p.locator('#modal').waitFor({state:'hidden'});}
async function visit(p,label,room){await p.locator('#journal').click();await button(p,'Walk to '+label).click();await p.waitForFunction(label=>!document.getElementById('interaction').hidden&&document.getElementById('interact-label').textContent===label,label,{timeout:15000});await p.keyboard.press('e');if(room)await p.waitForFunction(([key,room])=>JSON.parse(localStorage.getItem(key)).room===room,[G.key,room]);else await p.locator('#modal').waitFor({state:'visible'});}
async function start(p,id){await p.locator('#start').click();await p.getByRole('button',{name:/^Preview:/}).nth(['book','ledger','shelf'].indexOf(id)).click();assert.equal(await stored(p),null);await button(p,'Begin this Garden visit').click();await button(p,'Enter the garden court').click();}
function ready(id='book'){const s=G.preview(id);for(const a of ['fern','alignLight','latchShade','fernAgreement'])G.act(s,a);G.act(s,'place','shade');for(const a of ['alignReceiver','connect','listen','brimAgreement'])G.act(s,a);return s;}
async function journey(id,pair,place,evening){
 const p=await newPage(),source=G.preview(id).incoming,raw=JSON.stringify(source),archiveRaw=JSON.stringify(S.fresh());await p.evaluate(([t,r,a])=>{localStorage.setItem(t,r);localStorage.setItem('afterimage.prologue.v1',a);},[T.key,raw,archiveRaw]);await p.reload();await start(p,id);
 await visit(p,'Fern');assert.match(await p.locator('#dialog-body').innerText(),/I am Fern/);await close(p);
 await visit(p,'The open seat');const placeLabel={shade:'beneath the shade frame',receiver:'beside the receiver window',gate:'by the open gate'}[place];await button(p,'Place it '+placeLabel).click();assert.equal((await stored(p)).place,null);await button(p,'Reconsider').click();await button(p,'Place it '+placeLabel).click();await button(p,'Place the seat here').click();assert.equal((await stored(p)).place,place);
 assert.doesNotMatch(await p.locator('#dialog-body').innerText(),/repaired shade/);await button(p,'Sit with Fern for a while').click();assert.match(await p.locator('#dialog-body').innerText(),/shade is still unfinished/);assert.equal((await stored(p)).sharedMoment,false);await button(p,'Ask what this place is for').click();assert.match(await p.locator('#dialog-body').innerText(),/Fern smiles/);assert.equal((await stored(p)).sharedMoment,true);await close(p);
 await visit(p,'Glasshouse','glass');await visit(p,'Shade controls');assert.equal(await button(p,'Latch the shade').isDisabled(),true);await p.getByRole('button',{name:/^Turn reflector 1:/}).click();const partial=(await stored(p)).mirrors;await close(p);await p.reload();await p.locator('#start').click();assert.deepEqual((await stored(p)).mirrors,partial);await visit(p,'Shade controls');
 for(let i=0;i<4;i++)if((await stored(p)).mirrors[i]!==G.mirrorSolution[i])await p.getByRole('button',{name:new RegExp('^Turn reflector '+(i+1)+':')}).click();assert.equal((await stored(p)).shadeFixed,false);assert.equal(await button(p,'Latch the shade').isEnabled(),true);await p.screenshot({path:path.join(output,'garden-light.png')});await button(p,'Latch the shade').click();await close(p);assert.equal((await stored(p)).shadeFixed,true);
 await p.screenshot({path:path.join(output,'garden-glasshouse.png')});await visit(p,'Garden court','court');await visit(p,'Fern');await button(p,'Ask about the morning shade check').click();assert.equal((await stored(p)).fernAgreement,false);await button(p,'Record Fern’s offered job').click();assert.equal((await stored(p)).fernAgreement,true);await close(p);
 await visit(p,'Listening house','listening');await visit(p,'Call Brim');assert.match(await p.locator('#dialog-title').innerText(),/needs power/);await close(p);await visit(p,'Receiver workbench');assert.equal(await button(p,'Connect the receiver').isDisabled(),true);
 await p.getByRole('button',{name:/^Turn contact 1:/}).click();const contacts=(await stored(p)).contacts;await close(p);await p.reload();await p.locator('#start').click();assert.deepEqual((await stored(p)).contacts,contacts);await visit(p,'Receiver workbench');
 for(let i=0;i<3;i++)for(let n=0;n<3&&(await stored(p)).contacts[i]!==G.receiverLayout.solution[i];n++)await p.getByRole('button',{name:new RegExp('^Turn contact '+(i+1)+':')}).click();assert.equal((await stored(p)).receiverFixed,false);await p.screenshot({path:path.join(output,'garden-receiver.png')});await button(p,'Connect the receiver').click();await button(p,'Listen between the notices').click();assert.ok((await stored(p)).acquired.includes('tuning'));await close(p);
 await visit(p,'Call Brim');assert.equal((await stored(p)).brimAgreement,false);await button(p,'Record Brim’s offered job').click();assert.equal((await stored(p)).brimAgreement,true);await close(p);await visit(p,'Garden court','court');
 await p.locator('#journal').click();assert.equal(await button(p,'Walk to Silt').count(),source.siltReturned?1:0);await close(p);await p.screenshot({path:path.join(output,'garden-court-'+id+'.png')});
 await visit(p,'Courier handoff');for(const mem of pair)await p.getByRole('button',{name:new RegExp('^'+G.memories[mem].title)}).click();await button(p,'Review the two released memories').click();assert.equal((await stored(p)).cycle,1);for(const mem of G.candidates(await stored(p)).filter(mem=>!pair.includes(mem)))assert.ok((await p.locator('#dialog-body').innerText()).includes(G.memories[mem].loss));await button(p,'Reconsider').click();await button(p,'Review the two released memories').click();await button(p,'Release Courier 023').click();await p.waitForFunction(k=>JSON.parse(localStorage.getItem(k)).cycle===2,G.key);await p.locator('#transition.on').waitFor({state:'hidden'});assert.equal((await stored(p)).place,place);
 await visit(p,'Reopening ledger');assert.match(await p.locator('#dialog-title').innerText(),/Check the place/);await close(p);
 await visit(p,'The open seat');if(!pair.includes('fern'))assert.equal(await p.locator('#modal').getAttribute('data-scene'),'garden.seat-echo');else assert.equal(await p.locator('#modal').getAttribute('data-scene'),'garden.place');await button(p,'Sit for a moment').click();assert.match(await p.locator('#dialog-body').innerText(),pair.includes('fern')?/You remember sitting here with Fern/:/do not remember being here before/);assert.deepEqual((await stored(p)).kept,pair);await close(p);
 await visit(p,'Fern');assert.match(await p.locator('#speaker').innerText(),pair.includes('fern')?/A FAMILIAR INVITATION/:/A FIRST INVITATION/);if(pair.includes('fern'))assert.match(await p.locator('#dialog-body').innerText(),/dry leaf/);await close(p);
 await visit(p,'The open seat');assert.equal(await p.locator('#modal').getAttribute('data-scene'),'garden.place');assert.equal(await p.getByRole('button',{name:/^Place it/}).count(),0);assert.doesNotMatch(await p.locator('#dialog-body').innerText(),/Move it|will survive/);await button(p,'Sit for a moment').click();assert.match(await p.locator('#dialog-body').innerText(),pair.includes('fern')?/Fern puts down the tray and sits nearby/:/This is a new conversation/);await close(p);await visit(p,'Glasshouse','glass');await visit(p,'Shade controls');assert.equal(await button(p,'Latch the shade').count(),0);
 if(evening){await p.getByRole('button',{name:/^Plan an evening opening/}).click();assert.equal((await stored(p)).courierDuty,false);await button(p,'Leave the evening controller off').click();assert.equal((await stored(p)).courierDuty,false);await visit(p,'Shade controls');await p.getByRole('button',{name:/^Plan an evening opening/}).click();await button(p,'Accept the evening check').click();assert.equal((await stored(p)).courierDuty,true);}else{if(!pair.includes('sequence'))assert.equal(await p.getByRole('button',{name:/^Plan an evening opening/}).count(),0);await close(p);}
 await visit(p,'Garden court','court');await visit(p,'Listening house','listening');await visit(p,'Receiver workbench');assert.equal(await button(p,'Connect the receiver').count(),0);
 if(pair.includes('tuning')){await button(p,'Restore the quiet channel').click();assert.equal((await stored(p)).quiet,true);assert.match(await p.locator('#dialog-body').innerText(),/blank/);await close(p);}else{assert.equal(await button(p,'Restore the quiet channel').count(),0);assert.match(await p.locator('#dialog-body').innerText(),/was released/);await close(p);}
 await visit(p,'Garden court','court');await visit(p,'Reopening ledger');await p.getByRole('button',{name:new RegExp('^Review '+(evening?'daylight and evening opening':'daylight opening'))}).click();assert.equal((await stored(p)).open,null);await button(p,'Reconsider the hours').click();await p.getByRole('button',{name:new RegExp('^Review '+(evening?'daylight and evening opening':'daylight opening'))}).click();await button(p,'Confirm this opening').click();assert.equal((await stored(p)).open,evening?'evening':'daylight');assert.match(await p.locator('#dialog-body').innerText(),/Silt: no assigned duty/);
 const pending=p.waitForEvent('download');await button(p,'Export the opening record').click();const exported=G.validate(JSON.parse(fs.readFileSync(await (await pending).path(),'utf8')));assert.deepEqual(exported,await stored(p));assert.equal(await p.evaluate(k=>localStorage.getItem(k),T.key),raw);assert.equal(await p.evaluate(()=>localStorage.getItem('afterimage.prologue.v1')),archiveRaw);await p.screenshot({path:path.join(output,'garden-opening-'+id+'.png')});await p.reload();await p.locator('#start').click();assert.match(await p.locator('#speaker').innerText(),/OPENING RECORD/);await close(p);await visit(p,'The open seat');await button(p,'Sit for a moment').click();assert.equal(await p.locator('#modal').getAttribute('data-scene'),'garden.sitting-return');assert.deepEqual((await stored(p)).kept,pair);assert.equal((await stored(p)).open,evening?'evening':'daylight');await p.context().close();console.log('Garden full journey passed:',id,pair.join('+'),place,evening?'evening':'daylight');return exported;
}
async function mobileAndImports(completed){
 const p=await newPage(undefined,{width:390,height:844});await p.screenshot({path:path.join(output,'garden-mobile-cover.png')});await start(p,'book');await visit(p,'Fern');await close(p);await visit(p,'Glasshouse','glass');await visit(p,'Shade controls');await button(p,'Align the reflectors for me').click();assert.equal((await stored(p)).shadeFixed,false);assert.equal(await button(p,'Latch the shade').isEnabled(),true);assert.equal(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true);
 let controls=p.locator('#modal button:not(:disabled)');await controls.last().focus();await p.keyboard.press('Tab');assert.equal(await controls.first().evaluate(el=>el===document.activeElement),true);await p.keyboard.press('Shift+Tab');assert.equal(await controls.last().evaluate(el=>el===document.activeElement),true);await p.screenshot({path:path.join(output,'garden-mobile-light.png')});await button(p,'Latch the shade').click();await close(p);
 await visit(p,'Garden court','court');await visit(p,'Listening house','listening');await visit(p,'Receiver workbench');await button(p,'Align the contacts for me').click();assert.equal((await stored(p)).receiverFixed,false);await p.screenshot({path:path.join(output,'garden-mobile-receiver.png')});await button(p,'Connect the receiver').click();await close(p);
 await p.locator('#sound').click();assert.equal(await p.locator('#sound').getAttribute('aria-pressed'),'true');await p.locator('#sound').click();const before=(await stored(p)).player;await p.keyboard.down('ArrowDown');await p.waitForTimeout(500);await p.keyboard.up('ArrowDown');await p.evaluate(()=>window.dispatchEvent(new Event('blur')));assert.ok((await stored(p)).player.y-before.y>45);await p.screenshot({path:path.join(output,'garden-mobile-world.png')});
 const preserved=await stored(p);await p.locator('#help').click();await button(p,'Start a different Garden visit').click();await p.getByRole('button',{name:/^Preview:/}).first().click();await button(p,'Cancel').click();assert.deepEqual(await stored(p),preserved);
 const file=async value=>{await p.locator('#help').click();await p.locator('#import-file').setInputFiles({name:'record.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify(value))});};
 await file(T.fresh('stay'));await p.waitForFunction(()=>document.getElementById('speaker').textContent==='IMPORT FAILED');assert.deepEqual(await stored(p),preserved);await close(p);
 await file(completed);await button(p,'Import and continue').waitFor({state:'visible'});assert.deepEqual(await stored(p),preserved);await button(p,'Cancel').click();assert.deepEqual(await stored(p),preserved);
 await file(completed);await button(p,'Import and continue').click();assert.deepEqual(await stored(p),completed);await close(p);await file(G.preview('ledger').incoming);await button(p,'Import and continue').click();await button(p,'Enter the garden court').click();assert.equal((await stored(p)).incoming.origin,'obedience');assert.equal((await stored(p)).cycle,1);await p.context().close();
 const handoff=await newPage();const transit=G.preview('shelf').incoming,raw=JSON.stringify(transit);await handoff.goto(new URL('transit.html',base).href);await handoff.evaluate(([k,v])=>localStorage.setItem(k,v),[T.key,raw]);await handoff.reload();await handoff.locator('#start').click();await button(handoff,'Continue to Garden').click();await handoff.waitForURL(url);await handoff.locator('#start').click();await button(handoff,'Continue my Transit dispatch').click();await button(handoff,'Begin this Garden visit').click();await button(handoff,'Enter the garden court').click();assert.deepEqual((await stored(handoff)).incoming,transit);assert.equal(await handoff.evaluate(k=>localStorage.getItem(k),T.key),raw);await handoff.context().close();
 const bad=await newPage();await bad.evaluate(k=>localStorage.setItem(k,'{broken'),G.key);await bad.reload();await bad.locator('#start').click();assert.match(await bad.locator('#dialog-body').innerText(),/could not be read/);await bad.getByRole('button',{name:/^Preview:/}).first().click();await button(bad,'Cancel').click();assert.equal(await bad.evaluate(k=>localStorage.getItem(k),G.key),'{broken');await bad.context().close();
 const denied=await newPage();await denied.addInitScript(()=>Object.defineProperty(window,'localStorage',{get(){throw new DOMException('Denied','SecurityError');}}));await denied.reload();await denied.locator('#start').click();await denied.getByRole('button',{name:/^Preview:/}).first().click();await button(denied,'Begin this Garden visit').click();await button(denied,'Enter the garden court').click();await denied.locator('#help').click();const pending=denied.waitForEvent('download');await button(denied,'Export Garden (.json)').click();assert.equal(G.validate(JSON.parse(fs.readFileSync(await (await pending).path(),'utf8'))).cycle,1);await denied.context().close();
 console.log('Garden mobile assistance, focus, keyboard, audio, imports, confirmations, handoff, and storage-denied checks passed.');
}
async function additionalReturns(){
 const first=ready('book');for(const pair of [['greeting','sequence'],['greeting','tuning'],['sequence','fern'],['fern','tuning']]){const s=G.reset(first,pair),p=await newPage(s);await p.locator('#start').click();await visit(p,'Fern');assert.match(await p.locator('#speaker').innerText(),pair.includes('fern')?/A FAMILIAR INVITATION/:/A FIRST INVITATION/);await close(p);await visit(p,'Glasshouse','glass');await visit(p,'Shade controls');assert.equal(await p.getByRole('button',{name:/^Plan an evening opening/}).count(),pair.includes('sequence')?1:0);await close(p);await visit(p,'Garden court','court');await visit(p,'Listening house','listening');await visit(p,'Receiver workbench');assert.equal(await button(p,'Restore the quiet channel').count(),pair.includes('tuning')?1:0);await close(p);await visit(p,'Garden court','court');await visit(p,'Reopening ledger');await p.getByRole('button',{name:/^Review daylight opening/}).click();await button(p,'Confirm this opening').click();assert.equal((await stored(p)).open,'daylight');assert.equal((await stored(p)).courierDuty,false);await p.context().close();}
 console.log('All six greeting/sequence/Fern/tuning retention pairs have browser-tested returns.');
}
(async()=>{try{browser=await chromium.launch({headless:true});await journey('book',['sequence','tuning'],'shade',true);await journey('ledger',['greeting','fern'],'gate',false);const completed=await journey('shelf',['message','tuning'],'receiver',false);await mobileAndImports(completed);await additionalReturns();assert.deepEqual(errors,[]);console.log('Garden browser verification passed. Artifacts:',output);}catch(e){if(lastPage&&!lastPage.isClosed())await lastPage.screenshot({path:path.join(output,'garden-failure.png')}).catch(()=>{});throw e;}finally{await browser?.close();}})().catch(e=>{console.error(e);process.exitCode=1;});
