(function (root) {
  'use strict';
  const C = typeof module !== 'undefined' ? require('./chorus-state.js') : root.AfterimageChorus;
  const scene = (id, speaker, title, paragraphs) => ({ id: 'chorus.' + id, speaker, title, paragraphs });
  function record(s) { return [s.mode ? 'ROUTE / ' + C.modes[s.mode].title + '. ' + C.modes[s.mode].detail : 'ROUTE / Not connected.', 'GARDEN / ' + (s.incoming.open === 'evening' ? s.cycle === 1 ? 'Daylight and evenings, with Courier 024’s dusk check.' : s.evening === 'continue' ? 'Daylight and evenings. Courier 025 explicitly renewed the dusk check.' : 'Daylight continues. Evenings pause unless the new courier accepts the check with the retained sequence.' : 'Daylight hours. No evening duty assigned.'), 'TRANSIT / ' + (s.incoming.incoming.siltReturned ? 'Silt crossed back with the drawing.' : 'Silt remains on the far platform. A written copy of the drawing can travel without its author.')]; }
  const api = {
    record,
    arrival: s => scene('arrival', 'CHORUS / A PLACE TO DISAGREE', 'Three replies are waiting.', ['The carrier is the shared signal line. It needs inspection. Ask residents to pause their lamps, maintenance to disconnect the line, and dispatch to hold deliveries.', 'Start at the signal board. Connect a route, then use the inspection line to request and record all three approvals.', ...record(s)]),
    counter: s => scene('counter', 'COUNTER', s.cycle === 1 ? '“A queue is a way of not losing someone.”' : s.kept.includes('counter') ? '“You remember why I wanted the desk.”' : '“Then I should explain the desk again.”', [s.cycle === 1 ? '“These three requests concern the same fault,” Counter says. “I grouped them so maintenance would know.”' : s.kept.includes('counter') ? 'You remember Counter putting three requests together so no one would repair the same fault three times.' : 'Counter explains the queue again. You do not remember the first conversation.', '“But the system rejected Silt’s drawing because it had no fault code. It was a warning.”', '“Please include the drawing in your report.”']),
    receiver: s => scene('receiver', 'UNADDRESSED RECEIVER', s.cycle === 1 ? 'The designation field is blank.' : s.kept.includes('address') ? 'You remember this voice.' : 'Courier 025 has no memory of this voice.', s.cycle === 1 ? [s.incoming.seatEcho ? 'The receiver pauses for as long as you paused beside the empty seat.' : 'There is a pause where the courier designation would normally be read.', '“I am not addressing designation 024. I mean whoever keeps choosing which of us remembers.”', 'Counter is still sorting slips at the next desk. The voice is in this receiver alone.', '“Before you decide what to keep, listen to what we want.”'] : [s.kept.includes('address') ? 'You remember the voice asking you to listen before deciding.' : 'The courier sees a blank name field but does not remember the voice.', s.reply === 'listen' ? 'The written response is: “I will listen before deciding what to keep.”' : s.reply === 'space' ? 'The written response is: “I will leave this answer open.”' : 'Choose a promise to listen or leave the answer open. Neither choice restores a lost memory.']),
    ack: (s, group) => {
      const lines = { residents: 'Residents: you may turn off the garden lamps for this inspection only. Keep the garden open in daylight.', maintenance: 'Maintenance: the shared signal line is disconnected. Start inspection after all three groups approve. The fault’s cause is still unknown.', dispatch: 'Dispatch: deliveries will wait at the marked stops during inspection. Do not mark an unvisited platform empty.' };
      return scene('ack-' + group, 'COORDINATION / ACKNOWLEDGEMENT', group === 'combined' ? 'Counter’s combined envelope.' : group[0].toUpperCase() + group.slice(1) + ' reply.', group === 'combined' ? [lines.residents, lines.maintenance, lines.dispatch, 'All three approvals are here. Add Silt’s rejected warning to the report separately.'] : [lines[group]]);
    },
    handoff: s => scene('handoff', 'COURIER HANDOFF', 'The report can travel without its author.', ['The inspection is ready. Your report confirms people live in the garden and a warning was rejected. The fault’s cause is unknown.', 'Keep two of your four memories. The route, evidence, report, and approvals stay.', s.incoming.open === 'evening' ? 'The reset ends your dusk job. Courier 025 must keep the sequence and accept the check to reopen in the evening.' : 'The garden stays on daylight hours; no evening duty is inherited.']),
    receipt: s => scene('receipt', 'CHORUS / HANDOFF COMPLETE', 'Agreement with room in it.', [...record(s), 'REPORT / Inhabited garden. Warning filtered out. Cause of carrier loss not established.', s.reply === 'listen' ? 'RESPONSE / A promise to listen before choosing.' : 'RESPONSE / Room left for an answer.', 'Release will ask which part of this work should continue.'])
  };
  root.AfterimageChorusStory = api; if (typeof module !== 'undefined') module.exports = api;
})(typeof globalThis !== 'undefined' ? globalThis : this);
